<?php

/**
 * LogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Log');
    }
    
    public static function getAll() {
    	$q = Doctrine_Query::create()
    	     ->select("thetime, UNIX_TIMESTAMP(thetime) AS jstime, tair, rh, text ")
    	     ->from("Log") 
    	     ->orderBy("thetime asc");
    	$result = $q->execute(); 
    	
    	return $result ;
    }
}