# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         SmartFarm System
    description:   SmartFarm System
    keywords:      Hidroponik, Aquaponik
    language:      id
    robots:        index, follow

  stylesheets:    
                  - main.css

  javascripts:    
                  - /js/jquery/jquery.min.js
                  - /js/jquery/plugins/highcharts/highstock.js
                  - /js/jquery/plugins/highcharts/modules/exporting.js

  has_layout:     true
  layout:         layout
